version: '3.4'

services:
  discord-bot:
    image: ${DOCKER_REGISTRY-}discordbot
    build:
      context: .
      dockerfile: discord-bot/Dockerfile
    env_file:
      - env-variables.env
    restart: unless-stopped